### ISSUE TITLE
WebUI Default URL Not Working

### ISSUE THREAD

**Issue by mcgr0g** [sweisgerber/docker-mopidy#5]
I’m unable to access the Mopidy WebUI through the expected URLs. Here’s what I’ve tried:

-    http://localhost:6680/
-    http://localhost:6680/local/
-    http://localhost:6680/iris/

All attempts result in "The connection was reset". However, http://localhost:6600 works and returns the mpd version.

Running Mopidy via docker-compose.yml
```yaml
services:
  mopidy:
    image: docker.io/sweisgerber/mopidy:v3.4
    hostname: mopidy
    environment:
      - PUID=1000
      - PGID=1000
    restart: "unless-stopped"
    ports:
      - 6600:6600  # MPD port (works)
      - 6680:6680  # WebUI port (fails)
    volumes:
      - ./config/:/config/
      - ./data/:/data/
      - ./media/:/music/:ro
```
